# Generated by Django 5.2.4 on 2025-07-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user',
            new_name='user_id',
        ),
    ]
